name: Scramblies CI/CD

on:
  push:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Cache maven packages
      id: cache-m2
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('deps.edn') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@7.0
      with:
        cli: 1.11.1.1149
        
    - run: npm install
    
    - name: Compile js tests
      run: npx shadow-cljs compile test
      
    - name: Run cljs tests
      run: npm run test
        
    - name: Run tests
      run: clojure -M:test
        
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: eugenebakisov/scramblies:${{ steps.tag_version.outputs.new_tag }}
